blank_issues_enabled: false
contact_links:
  - name: 📚 Documentação
    url: https://github.com/suporte7company/FAQ/tree/2c85ae8691fe39b369b625b74db9c38760e8d139/docs
    about: Consulte a base de conhecimento antes de abrir uma issue
