SELECT 
ECF.ID_PROD,
ECF.DATA_EMISSAO,
PROPRI.DESCRICAO,
PROPRI.SINTEGRA_NCM
FROM ECF601 ECF

JOIN PRODUTOSPRINCIPAL PROPRI ON PROPRI.ID= ECF.ID_PRO

WHERE 
ECF.DATA_EMISSAO BETWEEN 'DATAINICIAL' AND 'DATAFINAL'
AND LENGHT (PROPRI.SINTEGRA_NCM) <> 8
